/**
 * AstralLounge 内置翻译文件
 */
const zh = {
  app: { title: 'AstralLounge', version: '版本', loading: '加载中...' },
  nav: { chat: '对话', groupChat: '群聊', characters: '角色', lorebooks: '世界', memory: '记忆', plugins: '插件', settings: '设置' },
  chat: { newSession: '新会话', noSessions: '暂无会话', selectCharacter: '选择角色', noCharacter: '无角色', startChat: '开始对话', typeMessage: '输入消息... (Enter 发送)', search: '搜索', send: '发送', thinking: 'AI 正在思考...', ghostMode: 'Ghost 防护', ghostOn: 'Ghost ON', ghostOff: 'Ghost OFF', ghostConfirm: '确认发送', ghostDiscard: '放弃', ghostPending: '待确认消息', tokenEstimate: '预估 tokens', autoExpire: '后自动放弃', webSearch: '网络搜索', searchResults: '搜索结果', noResults: '未找到相关结果', contextWarning: '上下文接近上限', contextFull: '上下文已满，建议开启新会话', export: '导出会话', import: '导入会话', rename: '重命名', delete: '删除', deleteConfirm: '确定要删除这个会话吗？', pinned: '置顶', unpinned: '取消置顶', groups: '会话分组', createGroup: '创建分组', groupName: '分组名称', groupColor: '分组颜色', allSessions: '全部会话', exportSuccess: '导出成功', importSuccess: '导入成功', model: '模型', temperature: '温度', maxTokens: '最大 Token', streamResponse: '流式响应', typingEffect: '打字机效果' },
  characters: { title: '角色管理', create: '创建角色', edit: '编辑', delete: '删除', export: '导出', import: '导入角色卡', noCharacters: '还没有角色', createFirst: '创建第一个角色', name: '角色名称', description: '角色描述', personality: '性格特征', scenario: '场景设定', greeting: '开场白', examples: '对话示例', tags: '标签', avatar: '角色头像', uploadAvatar: '点击上传', removeAvatar: '移除头像', importFormats: '支持多种格式：JSON、SillyTavern、TavernAI、PNG 嵌入等', pasteImport: '粘贴文本', fileImport: '上传文件', dropHere: '点击选择文件或拖拽到此处', exportFormat: '选择导出的格式', sillytavern: 'SillyTavern', tavernai: 'TavernAI', ooba: 'ooba / TextGen', json: 'JSON', confirmDelete: '确定要删除这个角色吗？', saveSuccess: '保存成功', deleteSuccess: '删除成功', importSuccess: '导入成功', exportSuccess: '导出成功', searchPlaceholder: '搜索角色...', filterByTag: '按标签筛选' },
  lorebooks: { title: '世界设定', create: '新建世界', noLorebooks: '还没有世界设定', createFirst: '创建第一个世界', name: '世界名称', description: '描述', insertMode: '插入方式', scanDepth: '扫描深度', contextLength: '上下文长度', forceActivation: '强制注入', exclusion: '排除标签', keyword: '关键词', entries: '条目', entryName: '条目名称', entryContent: '条目内容', keywords: '触发关键词', priority: '优先级', enabled: '启用', addEntry: '添加条目', editEntry: '编辑条目', deleteEntry: '删除条目', confirmDelete: '确定要删除这个条目吗？', confirmDeleteBook: '确定要删除整个世界设定吗？', saveSuccess: '保存成功', deleteSuccess: '删除成功', import: '导入', export: '导出', batchDelete: '批量删除', preview: '预览' },
  memory: { title: '记忆管理', add: '添加记忆', noMemories: '暂无记忆', addFirst: '添加第一条记忆', content: '内容', titleLabel: '标题', category: '分类', tags: '标签', importance: '重要性', source: '来源', accessCount: '访问次数', created: '创建时间', auto: '自动', manual: '手动', stats: { total: '记忆总数', sessions: '会话数', longTerm: '长期记忆', categories: '分类数' }, searchPlaceholder: '搜索记忆...', filterByCategory: '按分类筛选', sortBy: '排序', newest: '最新优先', oldest: '最旧优先', byImportance: '按重要性', byAccess: '最近访问', confirmDelete: '确定要删除这条记忆吗？', saveSuccess: '保存成功', deleteSuccess: '删除成功', clearAll: '清空所有记忆', exportMemories: '导出记忆', importMemories: '导入记忆' },
  groupChat: { title: '群聊', create: '新建', noGroups: '还没有群聊', createFirst: '点击上方"新建"创建一个', members: '个角色', addCharacter: '添加角色到群聊', chatMode: '发言模式', rotation: '轮流发言', orchestrator: '主持人模式', selectSession: '选择一个群聊或新建群聊', groupReady: '群聊已就绪！发送消息开始对话', hint: '轮流发言模式下，AI 会依次以不同角色回复', startChat: '群聊已就绪', noCharacters: '点击 + 添加角色', noCharsAvailable: '还没有角色，请先去角色管理创建', groupName: '群聊名称', noResults: '暂无搜索结果' },
  plugins: { title: '插件与系统管理', market: '插件市场', skills: '技能管理', quickInstall: '一键安装插件', installPlaceholder: '输入 GitHub 仓库地址，例如: AstralLounge/example-plugin', installButton: '安装', installing: '安装中...', noPlugins: '暂无插件', installHint: '在上方输入 GitHub 仓库地址来安装插件', skillsStats: { total: '总技能', enabled: '已启用' }, noSkills: '暂无技能', skillsHint: '技能文件将自动加载到 backend/plugins/skills 目录', reload: '重载', enable: '启用', disable: '禁用', uninstall: '卸载', install: '安装', installed: '已安装', author: '作者', version: '版本', category: '分类', featured: '推荐插件', installedTab: '已安装', searchResults: '搜索结果', searchPlaceholder: '搜索 GitHub 插件...', searchButton: '搜索', installSuccess: '安装成功', uninstallSuccess: '卸载成功', reloadSuccess: '重载成功' },
  settings: { title: '设置', model: '模型', memory: '记忆', tts: '语音', ui: '界面', about: '关于', safety: '安全', advanced: '高级', provider: 'AI 提供商', modelName: '模型名称', apiUrl: 'API 地址', temperature: '温度参数', maxTokens: '最大 Token', topP: 'Top P', presencePenalty: 'Presence Penalty', frequencyPenalty: 'Frequency Penalty', testConnection: '测试连接', refreshModels: '刷新模型列表', testing: '测试中...', connectionSuccess: '连接成功', connectionFailed: '连接失败', redisEnabled: '启用 Redis 缓存', shortTermLimit: '短期记忆容量', ragEnabled: '启用 RAG 长期记忆', vectorDb: '向量数据库', embeddingModel: 'Embedding 模型', cosyvoiceEnabled: '启用 CosyVoice', cosyvoiceUrl: 'CosyVoice 地址', gptsovitsEnabled: '启用 GPT-SoVITS', gptsovitsUrl: 'GPT-SoVITS 地址', defaultVoice: '默认音色', speechSpeed: '语速', testVoice: '测试语音', theme: '主题模式', darkTheme: '深色', lightTheme: '浅色', accentColor: '主题颜色', typingEffect: '打字机效果', streamResponse: '流式响应', compactMode: '紧凑模式', language: '语言', safetyEnabled: '启用安全过滤', blockEnabled: '启用内容拦截', logEnabled: '记录日志', sensitiveAction: '敏感内容处理', blockAction: '拦截动作', sensitiveWords: '敏感词', blockedWords: '拦截词', addWord: '添加词语', confirmUninstall: '确定要卸载这个插件吗？', appName: 'AstralLounge', version: '版本', versionNumber: '1.0.0', description: '现代化本地 AI 对话平台', debugMode: '开发模式', saveSuccess: '保存成功', saveFailed: '保存失败', reset: '重置', resetConfirm: '确定要重置所有设置为默认值吗？' },
  common: { save: '保存', cancel: '取消', confirm: '确认', close: '关闭', delete: '删除', edit: '编辑', create: '创建', add: '添加', search: '搜索', loading: '加载中...', success: '操作成功', error: '操作失败', warning: '警告', info: '提示', yes: '是', no: '否', ok: '确定', back: '返回', next: '下一步', prev: '上一步', refresh: '刷新', copy: '复制', copied: '已复制', download: '下载', upload: '上传', noData: '暂无数据', retry: '重试', noPermission: '无权限' },
  time: { justNow: '刚刚', minutesAgo: '{n}分钟前', hoursAgo: '{n}小时前', daysAgo: '{n}天前', weeksAgo: '{n}周前' },
  errors: { networkError: '网络错误，请检查网络连接', serverError: '服务器错误，请稍后重试', unknownError: '发生未知错误', timeout: '请求超时', notFound: '未找到', unauthorized: '未授权', forbidden: '禁止访问' }
}

const en = {
  app: { title: 'AstralLounge', version: 'Version', loading: 'Loading...' },
  nav: { chat: 'Chat', groupChat: 'Group Chat', characters: 'Characters', lorebooks: 'Worlds', memory: 'Memory', plugins: 'Plugins', settings: 'Settings' },
  chat: { newSession: 'New Session', noSessions: 'No sessions', selectCharacter: 'Select Character', noCharacter: 'No Character', startChat: 'Start Chat', typeMessage: 'Type a message... (Enter to send)', search: 'Search', send: 'Send', thinking: 'AI is thinking...', ghostMode: 'Ghost Protection', ghostOn: 'Ghost ON', ghostOff: 'Ghost OFF', ghostConfirm: 'Confirm', ghostDiscard: 'Discard', ghostPending: 'Pending', tokenEstimate: 'Est. tokens', autoExpire: 'auto-discard in', webSearch: 'Web Search', searchResults: 'Results', noResults: 'No results', contextWarning: 'Context limit', contextFull: 'Context full', export: 'Export', import: 'Import', rename: 'Rename', delete: 'Delete', deleteConfirm: 'Delete this session?', pinned: 'Pin', unpinned: 'Unpin', groups: 'Groups', createGroup: 'Create Group', groupName: 'Group Name', groupColor: 'Color', allSessions: 'All Sessions', exportSuccess: 'Exported', importSuccess: 'Imported', model: 'Model', temperature: 'Temperature', maxTokens: 'Max Tokens', streamResponse: 'Stream', typingEffect: 'Typing Effect' },
  characters: { title: 'Characters', create: 'Create', edit: 'Edit', delete: 'Delete', export: 'Export', import: 'Import Card', noCharacters: 'No characters', createFirst: 'Create first character', name: 'Name', description: 'Description', personality: 'Personality', scenario: 'Scenario', greeting: 'Greeting', examples: 'Examples', tags: 'Tags', avatar: 'Avatar', uploadAvatar: 'Upload', removeAvatar: 'Remove', importFormats: 'Supports JSON, SillyTavern, TavernAI, PNG', pasteImport: 'Paste', fileImport: 'Upload File', dropHere: 'Click or drag file here', exportFormat: 'Select format', sillytavern: 'SillyTavern', tavernai: 'TavernAI', ooba: 'ooba / TextGen', json: 'JSON', confirmDelete: 'Delete this character?', saveSuccess: 'Saved', deleteSuccess: 'Deleted', importSuccess: 'Imported', exportSuccess: 'Exported', searchPlaceholder: 'Search...', filterByTag: 'Filter by tag' },
  lorebooks: { title: 'World Settings', create: 'Create World', noLorebooks: 'No worlds', createFirst: 'Create first world', name: 'Name', description: 'Description', insertMode: 'Insert Mode', scanDepth: 'Scan Depth', contextLength: 'Context Length', forceActivation: 'Force', exclusion: 'Exclude', keyword: 'Keyword', entries: 'Entries', entryName: 'Entry Name', entryContent: 'Content', keywords: 'Keywords', priority: 'Priority', enabled: 'Enabled', addEntry: 'Add Entry', editEntry: 'Edit', deleteEntry: 'Delete', confirmDelete: 'Delete this entry?', confirmDeleteBook: 'Delete this world?', saveSuccess: 'Saved', deleteSuccess: 'Deleted', import: 'Import', export: 'Export', batchDelete: 'Batch Delete', preview: 'Preview' },
  memory: { title: 'Memory', add: 'Add', noMemories: 'No memories', addFirst: 'Add first memory', content: 'Content', titleLabel: 'Title', category: 'Category', tags: 'Tags', importance: 'Importance', source: 'Source', accessCount: 'Access', created: 'Created', auto: 'Auto', manual: 'Manual', stats: { total: 'Total', sessions: 'Sessions', longTerm: 'Long-term', categories: 'Categories' }, searchPlaceholder: 'Search...', filterByCategory: 'Filter by category', sortBy: 'Sort', newest: 'Newest', oldest: 'Oldest', byImportance: 'By Importance', byAccess: 'Recently Accessed', confirmDelete: 'Delete this memory?', saveSuccess: 'Saved', deleteSuccess: 'Deleted', clearAll: 'Clear All', exportMemories: 'Export', importMemories: 'Import' },
  groupChat: { title: 'Group Chat', create: 'New', noGroups: 'No groups', createFirst: 'Click New to create', members: 'members', addCharacter: 'Add Character', chatMode: 'Mode', rotation: 'Rotation', orchestrator: 'Orchestrator', selectSession: 'Select or create group', groupReady: 'Ready! Send message', hint: 'AI responds with different characters in turn', startChat: 'Ready', noCharacters: 'Click + to add', noCharsAvailable: 'No characters, create first', groupName: 'Group Name', noResults: 'No results' },
  plugins: { title: 'Plugins & System', market: 'Market', skills: 'Skills', quickInstall: 'Quick Install', installPlaceholder: 'Enter GitHub repo...', installButton: 'Install', installing: 'Installing...', noPlugins: 'No plugins', installHint: 'Enter repo URL to install', skillsStats: { total: 'Total', enabled: 'Enabled' }, noSkills: 'No skills', skillsHint: 'Auto-loads from skills folder', reload: 'Reload', enable: 'Enable', disable: 'Disable', uninstall: 'Uninstall', install: 'Install', installed: 'Installed', author: 'Author', version: 'Version', category: 'Category', featured: 'Featured', installedTab: 'Installed', searchResults: 'Results', searchPlaceholder: 'Search...', searchButton: 'Search', installSuccess: 'Installed', uninstallSuccess: 'Uninstalled', reloadSuccess: 'Reloaded' },
  settings: { title: 'Settings', model: 'Model', memory: 'Memory', tts: 'Voice', ui: 'Interface', about: 'About', safety: 'Safety', advanced: 'Advanced', provider: 'Provider', modelName: 'Model', apiUrl: 'API URL', temperature: 'Temperature', maxTokens: 'Max Tokens', topP: 'Top P', presencePenalty: 'Presence Penalty', frequencyPenalty: 'Frequency Penalty', testConnection: 'Test', refreshModels: 'Refresh', testing: 'Testing...', connectionSuccess: 'Success', connectionFailed: 'Failed', redisEnabled: 'Redis Cache', shortTermLimit: 'Short-term Limit', ragEnabled: 'RAG Memory', vectorDb: 'Vector DB', embeddingModel: 'Embedding Model', cosyvoiceEnabled: 'CosyVoice', cosyvoiceUrl: 'CosyVoice URL', gptsovitsEnabled: 'GPT-SoVITS', gptsovitsUrl: 'GPT-SoVITS URL', defaultVoice: 'Voice', speechSpeed: 'Speed', testVoice: 'Test Voice', theme: 'Theme', darkTheme: 'Dark', lightTheme: 'Light', accentColor: 'Color', typingEffect: 'Typing Effect', streamResponse: 'Stream', compactMode: 'Compact', language: 'Language', safetyEnabled: 'Safety Filter', blockEnabled: 'Block Content', logEnabled: 'Log Actions', sensitiveAction: 'Sensitive Action', blockAction: 'Block Action', sensitiveWords: 'Sensitive Words', blockedWords: 'Blocked Words', addWord: 'Add', confirmUninstall: 'Uninstall this plugin?', appName: 'AstralLounge', version: 'Version', versionNumber: '1.0.0', description: 'Modern Local AI Chat Platform', debugMode: 'Debug', saveSuccess: 'Saved', saveFailed: 'Failed', reset: 'Reset', resetConfirm: 'Reset all settings?' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', close: 'Close', delete: 'Delete', edit: 'Edit', create: 'Create', add: 'Add', search: 'Search', loading: 'Loading...', success: 'Success', error: 'Error', warning: 'Warning', info: 'Info', yes: 'Yes', no: 'No', ok: 'OK', back: 'Back', next: 'Next', prev: 'Prev', refresh: 'Refresh', copy: 'Copy', copied: 'Copied', download: 'Download', upload: 'Upload', noData: 'No data', retry: 'Retry', noPermission: 'No permission' },
  time: { justNow: 'Just now', minutesAgo: '{n}m ago', hoursAgo: '{n}h ago', daysAgo: '{n}d ago', weeksAgo: '{n}w ago' },
  errors: { networkError: 'Network error', serverError: 'Server error', unknownError: 'Unknown error', timeout: 'Timeout', notFound: 'Not found', unauthorized: 'Unauthorized', forbidden: 'Forbidden' }
}

export { zh, en }
